services:
  mssql2025:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    ports:
      - "14333:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backups:/var/opt/mssql/backups
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
